### PR TITLE
memsource support

### PR DESCRIPTION
**Pull request by sundeep-anand**
This effort is to add [Memsource](https://cloud.memsource.com/) support in Transtats.

To Do:
- [X] Add Memsource API configurations.
- [x] Try and Test APIs. Analyse. Make db provisions.
- [x] Memsource Platform UI changes.
- [x] Memsource auth implementation. Project details API.
- [X] Projects API. Add CI Pipeline(s).
- [x] List CI Pipeline(s). Remove/hide them.
- [x] Create Project/jobs, push-translate-pull translations.
- [x] Code cleanups, overall tests.

### CODE REVIEW

**Comment by sundeep-anand** [comment]
## Notes

### Authentication

Options we have with [Memsource](https://help.memsource.com/hc/en-us/articles/360014441359-REST-API-Authentication) are:

1. Token, which remains valid for 24 hours and can be used for all subsequent calls.
2. OAuth 2.0

As internal `OAuth 2.0 call back uri` may not be accessible from memsource cloud, we may need to go with **Token** approach. So, requesting a new token as soon as one expires.

### Implementation

Memsource is far different than `Zanata` `Weblate` `Tx` in - as it is designed. 
Its around re-usability, integrations and focused (_smaller_) jobs for translation.

#### 1st Approach

Just as an another translation platform. Project URLs would be based on the **uuid** (_making `project_slug` less important here_). Project jobs could be seen as `project_versions`!

##### Advantage

Package relationship will remain intact: <code>1 Package : 1 Translation Platform</code> Less UI and back-end changes. High level composition may look similar and can be distinguished broadly. Less code changes, refactor in jobs too.

##### Disadvantage

- Memsource statistics API are not similar to that of other translation platform(s). Here, each `project_job` can be seen as one language (_one PO file_) whereas with other platforms each `project_version` or `project_component` may has multiple languages. Furthermore, statistics are not that verbose - they're abstracted under **Analyses**.

- Project URL(s) in Transtats are static across releases. And they are validated (_remain in sync_) with translation platform. This is contradictory to the requirement where we may have different project URL(s) for each release.

#### 2nd Approach

Add and list Memsource just as an another translation platform. Create a CI pipeline module in Transtats.
This may change the relationship to <code>1 Package : 1 Translation Platform : 1 CI Platform</code>. Multiple CI pipelines could be created (_and maintained_) for a package. 

Each CI pipeline would be linked with
- 1 Package 
- 1 CI Platfrom (_for example memsource_)
- 1 Release (_release language set will be overridden by `memsource_project_target_langs`_)
- 1 Push (_source repo to memsource_) Job Template
- 1 Pull (_memsource to source repo_) Job Template
- X (_multiple_) CI Platform Jobs
- _other details_

##### Advantage

- Atomic, self contained design. Shall look much cleaner.
- UI components related to CI pipeline will only be loaded if required. This will not impact existing packages. (_pointing to`Zanata` `Weblate` `Tx`_)
- More focused and adequate components could be developed as per CI requirements.
- Package details page shall continue to show all information. A new section CI can be expected.

##### Disadvantage

Transtats components which are based on translation platform statistics for example: treading languages, estimation for a release (_release trends_), coverage rules shall not include statistics from CI platform. Hence, a few of them need to be adjusted to include statistics from CI platform where-ever required.

### Scope

- Integrate all required API(s) to automate workflow.
- CI pipeline back-end and front-end implementations.

#### Improvements

With the **2nd approach**, as discussed above - specialized functionalities could be developed and tweaked in the future.
It has the breadth to host an array of possibilities to automate a lot more workflows: `workflowSteps`, `TM`, `MT`, `segments` etc.

---

@ludekjanda @juhp @krisnababu seeking your thoughts? comments?

**Comment by sundeep-anand** [comment]
**+** Memsource project lifecycle details are [here](https://help.memsource.com/hc/en-us/articles/115003843132-Data-Storage).

**Comment by ludekjanda** [comment]
I love the 2nd approach @sundeep-anand . Regarding the statistics in Memsource. The true is that detailed stats can be fetched through Analysis only. However, basic wordcounts do not need stats, they may be received through a simple API call against a job
https://cloud.memsource.com/web/docs/api#operation/getPart "wordsCount": 0, 
In Memsource GUI these easy to get stats show up when hovering a job (the percentage of completeness) .

Regarding the jobs, Memsource has 2 ways to upload jobs. One of them supports continous translation, ie, the same job gets overwritten with the latest versions. It would be great if the new Transtats CI module could support that. https://cloud.memsource.com/web/docs/api#operation/createJob continuous - true for continuous job

**Comment by sundeep-anand** [comment]
followed by https://github.com/transtats/transtats/pull/223

**Comment by ludekjanda** [comment]
The last news we got from memsource are rather bad. 

Memsource Support ticket #69671

They say: 

> 
> When you import a job from a repository as CJ, source files are continuously monitored for changes. No need for any manual interaction. 
> You can also set how often do you want system to export the jobs back to the repository. 

> So when you use the create job api, it will get the file from the connector, and from there, everything should happen automatically. 

> Steps to be taken: 

> Get the connector token: https://cloud.memsource.com/web/docs/api#operation/getConnector
connector ID that is required for this call can be found in the URL of the connector setup page: https://drops.memsource.com/Kouw8eR4 
> In the response you get the connector token that is required for the job creation call. 

> Then in the create job call, in the header you can specify the connector token, folder, and the file to be imported

To sum it up, according to them we can use API call to: 
- create a new continuous project and upload a job there. 
But that's it it. After this initial push, the updates will be regulated by Memsource itself and its CRON settings.

@sundeep-anand we may need to re-figure out our workflow then. Transtats could create initial project, set up it's sync settings. But there would be no need to set up a CRON job on Transtats side.

**Comment by sundeep-anand** [comment]
@krisnababu kindly consider push translations change for testing!

**Comment by sundeep-anand** [comment]
new commits fee72dc - 623c69b includes:
 - Push Job Implementation
 - Refresh CI Pipeline

**Comment by sundeep-anand** [comment]
for more details, read [connectors](https://help.memsource.com/hc/en-us/articles/360012106840-Box-Connector) and [continuous jobs](https://help.memsource.com/hc/en-us/articles/360014179800-Continuous-Jobs) in memsource!

**Comment by sundeep-anand** [comment]
More ToDo:

- [ ] CI Pipeline Configurations: Push, Pull, Update Jobs
- [ ] Celery settings for background jobs 
- [ ] Overall checks

**Comment by sundeep-anand** [comment]
> More ToDo:
> 
> * [ ]  CI Pipeline Configurations: Push, Pull, Update Jobs
> * [ ]  Celery settings for background jobs
> * [ ]  Overall checks

To be covered in following changes.

**Comment by sundeep-anand** [comment]
finally merging this to `devel`, target shipment `release_0.8.2`

**Pull request merged**
