### PR TITLE
better UI

### PR DESCRIPTION
**Pull request by sundeep-co-in**
##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY

Use-Cases Based UI designs

ToDo
 - [x] Enhance Package Details Page
 - [x] Autosync Packages with Build System (*determine out-of-sync packages*)
 - [x] Add Language Details Page (*for Language Maintainers*)
 - [x] Revamp Landing Page
 - [x] deployment and overall checks

---
 - [ ] release testing `envs` `blank db` `roles` `APIs`
 - [ ] update `docs` `website`

Issue #177 
Issue #169 
Issue #168

### CODE REVIEW

**Comment by sundeep-co-in** [comment]
@spathare21 Kindly consider this for testing ..

**Comment by spathare21** [comment]
Hi @sundeep-co-in 

Perform some testing and below are the observations. 

- On dashboard it shows “Data not found” for  out of sync.
- On Dashboard Trending languages shows stats shows only abrt messages count. 

stats_dashboard

- On Dashboard product release readiness what should be expected to show ?. 
- Translation platform statistics shows on language details page shows 100 % and if we click on details it shows 1.7% remaining. e.g french, german

lang_stats


- Unable to run 2 package upstream sync parallel  1 failed with error

Will cover more scenarios/tests and will let you know the details .

**Comment by sundeep-co-in** [comment]
> On dashboard it shows “Data not found” for out of sync.

That's okay - packages should be sync'd with build system and have `diff`to appear in this!
Run `./manage syncpackages`  -- to sync packages!
 
> On Dashboard Trending languages shows stats shows only abrt messages count.

I guess branch mapping of `abrt` for `fedora 31` would only be accurate. Here system detects latest release and pulls out stats as per it's branch mapping.

>  On Dashboard product release readiness what should be expected to show.

Once, we have stats from build system for latest release, packages are mapped to, it should be populated. You can select country/territory for insights.

> Translation platform statistics shows on language details page shows 100 % and if we click on details it shows 1.7% remaining. e.g french, german

let me see, this is unexpected.

> Unable to run 2 package upstream sync parallel 1 failed with error.

That's okay - we have an issue for this!

**Comment by spathare21** [comment]
Hi @sundeep-co-in ,

Tested most of the functionality and looks no blocker. 

- Instead of details button on out of sync on dashboard link of details will look good. 

dashboard_trans

-  Buttons on Sync job gets miss-aligned with text in smaller view

jobs_sycn

- List of lang shows on territory view on right side is it needed ? 

Territory_view_lang

- Jobs sync for packages takes more time may be due to my local docker env. 

We can go ahead for the release 

Thanks,
Sachin

**Comment by sundeep-co-in** [comment]
thank you so much @spathare21 for taking a look ...

> Instead of details button on out of sync on dashboard link of details will look good.

done

> Buttons on Sync job gets miss-aligned with text in smaller view

fixed

> List of lang shows on territory view on right side is it needed ?

Yes - for use-case where user might want to know locales for a given territory, irrespective of related data we have in Transtats.

>  Jobs sync for packages takes more time may be due to my local docker env.

(*might be*)

**Pull request merged**
