### PR TITLE
release 0.1.5-rc.1

### PR DESCRIPTION
**Pull request by sundeep-co-in**
`release 0.1.5-rc.1 PR`

- [x] Test with blank db and test_data
- [x] Check all workflow, may be automated testing
- [x] Rebuild both container image: dev, test

### CODE REVIEW

**Comment by sundeep-co-in** [comment]
@spathare21 Please do a quick pre-release testing.

**Comment by spathare21** [comment]
@sundeep-co-in Tested the above-mentioned things in dev and test env in vagrant and container also tested things in python virtual env and all is working fine except below two things I noticed for which I am not sure its bug or I am doing wrong. 

- Error while deactivating Translation platform "Translation Platform with ID "3" doesn't exist. Perhaps it was deleted?", If we delete 3rd translation platform and then try to deactivate next 3rd or 4th translation platform

screenshot from 2018-02-01 12-25-19


- Staff user able to see Add language, edit language,Add and manage translation platform, Product ..etc and on clicking it returns 403 forbidden.

screenshot from 2018-02-01 15-31-11

screenshot from 2018-02-01 15-38-12
screenshot from 2018-02-01 15-43-40

**Comment by sundeep-co-in** [comment]
@spathare21 thanks, you may please resume!

**Comment by spathare21** [comment]
@sundeep-co-in sometimes I see translation platform UI like this. did make static before running make demo in vagrant env. 

screenshot from 2018-02-01 18-20-47

screenshot from 2018-02-01 18-20-08

**Comment by spathare21** [comment]
thanks @sundeep-co-in  working fine now : )

**Pull request merged**
