### PR TITLE
New dashboard using PatternFly

### PR DESCRIPTION
**Pull request by bhavin192**
##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY
- This fixes all the conflicts from #136 
- Some initial efforts for Jobs section
- Switch to latest version of PatternFly
- Adds `jquery.flot` (0.8.3), `jquery.flot.tooltip` (0.9.0) as dependency
  for Transtats

Issue #28

### CODE REVIEW

**Comment by sundeep-co-in** [comment]
thank you so much @bhavin192 for sorting this out! moving this to testing ... :+1:

**Comment by sundeep-co-in** [comment]
@spathare21 please have a quick look and start testing this ..

**Comment by spathare21** [comment]
Hi,

Started testing new UI and below are the few initial observations 

- Have we added a logo for transtats ?  image looks broken
screenshot from 2018-12-28 16-54-17

- Server Error(500) on login click 

screenshot from 2018-12-28 16-54-46


- Project Docs should open in a new tab 
- Add package throws 'Server Error(500)'
- Sync package upstream throws HTTP error 405
- On create graphs rule  it throws 'server error(500)'

**Comment by bhavin192** [comment]
@spathare21 thank you for initial testing, 

> Have we added a logo for transtats ? image looks broken

No we don't have a logo as of now, I will create one and add it there later.
> Sync package upstream throws HTTP error 405

From where are you invoking this action? From the package's page or from Jobs section?

**Comment by sundeep-co-in** [comment]
Please `rebase` these changes with the base branch.

**Comment by spathare21** [comment]
@bhavin192 , getting error while make static please see traceback here https://pastebin.com/Nqr9HbFt

**Comment by sundeep-co-in** [comment]
closing against https://github.com/transtats/transtats/pull/160

**Pull request closed without merging**
