### PR TITLE
add koji

### PR DESCRIPTION
**Pull request by sundeep-co-in**
##### ISSUE TYPE

 - Feature Pull Request

Issue https://github.com/transtats/transtats/issues/65

- [x] Calculate translation stats from SRPM
- [x] Create better interface for YML Based Job
- [x] Create Sync Build Tags Job
- [x] Improve `downstream` manager code
- [x] Include build tags in package branch mapping
- [x] Extend the support/feature for brew also
- [x] Integrate collected stats to `Package View` and `Reports`
- [x] Recheck `branch mapping` and fix blocker
- [x] Test for vagrant/docker-hub and fix travis-ci build failure
- [x] Include `YAML Based Jobs` in docs, improve overall
- [x] Fix reported bugs and minify `css and js`
- [ ] Make this change ready for openshift deployment

` - testing complete`

### CODE REVIEW

**Comment by sundeep-co-in** [comment]
thanks @sshedmake 
#**blocker** Patches found in `SRPM` must be applied before we calculate statistics.

**Comment by pravins** [comment]
Thanks @sshedmake  for identifying this blocker issue.

**Comment by sundeep-co-in** [comment]
migrating from `Travis` to `CircleCI`

**Comment by sundeep-co-in** [comment]
Pushing this change to `devel` 
Will take `openshift readiness` with `release_0.1.5-rc.2` PR

**Pull request merged**
